### ISSUE TITLE
Links of about-dialog opens in new CCA-window

### ISSUE THREAD

**Issue by WillyLaudehr** [ThePacielloGroup/CCAe#274] opened 2022-12-01 11:07 UTC
**Describe the bug**
From about-dialog follow hyperlink to Github
active CCA-dialog follows hyperlink, page is not shown in system-default browser
problem: Window has no address bar and is not sizable
Strg+click open link in new CCA-window, but that's not really better

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64 bits
 - Version 21H2
 - CCA 3.2.0

**To Reproduce**
see describe, that's all

**Expected behavior**
Links has to be opened in system-default browser

**Screenshots**
![grafik](https://user-images.githubusercontent.com/71374728/205037320-016ddc1f-fdb3-4c4a-9b25-6a0099102b51.png)

**Comment by ferllings** [comment] 2022-12-01 11:09
Duplicate of #260

**Closed by ferllings** 2022-12-01 11:09 UTC
Labels: duplicate
