### ISSUE TITLE
Application version not shown in About dialog

### ISSUE THREAD

**Issue by gtritchie** [ThePacielloGroup/CCAe#283] opened 2023-03-01 21:59 UTC
**Describe the bug**
The product version is missing in the About dialog on macOS.

<img width="412" alt="screenshot of About dialog with no version showing" src="https://user-images.githubusercontent.com/10569626/222271491-0a23858c-dd95-430c-89f8-3a4c438d8594.png">

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.2.1 (M1)
 - Version 3.2

**To Reproduce**
1. Download macOS version from https://www.tpgi.com/color-contrast-checker/, open DMG, drag app to Applications, then start from Applications.
2. Show the About CCA dialog (from application menu)

**Expected behavior**
It should show the product version number. I cloned the repo and built it myself, and I do see the version in my local build:

<img width="412" alt="Screenshot of About dialog showing version" src="https://user-images.githubusercontent.com/10569626/222271623-146020d0-b872-4860-baa5-fb39d5a9332c.png">

**Screenshots**
See above.

**Additional context**
None

**Comment by poorgeek** [comment] 2023-03-02 02:58
Duplicate of #255 and will be included in next release.

**Closed** 2023-03-02 02:58 UTC
