### ISSUE TITLE
CCA not functioning properly

### ISSUE THREAD

**Issue by LTann74** [ThePacielloGroup/CCAe#162] opened 2020-04-01 13:33 UTC
Never had this with the old CCA, now I can only do one comparison and it freezes; sometimes after choosing the eyedropper the cursor moves in slow motion. After doing one color comparison it generally freezes, often the red X in upper right gets grayed out, I click and it asks if I want to close the program, I do, then get an error window that says Auto Update Error: Error: spawn EACCES with a lot more text I cannot retype here as there's too much - most lines begin with "Files\CCA\resources\app.asar\node_modules\electron-updater..." etc.
Ive redownloaded and it seems to make no difference.

PC using Windows 10

I expect the program to remain open and functional as long as i require it, to text multiple colors within one document

![image](https://user-images.githubusercontent.com/63000793/78143050-b4787480-73fb-11ea-87bd-565f09cd7641.png)

**Comment by ferllings** [comment] 2020-04-01 13:42
Duplicate of #158

**Closed by ferllings** 2020-04-01 13:42 UTC
