### ISSUE TITLE
No ability to zoom

### ISSUE THREAD

**Issue by mlamond** [ThePacielloGroup/CCAe#108] opened 2019-04-17 19:20 UTC
**Describe the bug**
I'm unable to zoom in/out using the keyboard and there is no zoom feature in the View menu.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 8 64 bits]
 - Version [e.g. 1.1.1]

**To Reproduce**
Click View on menu, or Ctrl+/- on Windows

**Expected behavior**
Zoom in/out, or see zoom in/out in View menu

**Screenshots**
![image](https://user-images.githubusercontent.com/43453361/56314853-3d7f9880-6124-11e9-834d-347ef98a735a.png)

**Additional context**

**Comment by patrickhlauke** [comment] 2019-04-17 19:22
It works and behaves like a regular native application, so there is currently no provision for zooming of the app content/interface

**Comment by ferllings** [comment] 2019-04-17 19:56
There is a zooming capability, but the problem is to capture the event, in order to adjust the window size (See #38)

**Comment by ferllings** [comment] 2019-04-19 15:25
Fixed in #112

**Closed by ferllings** 2019-04-19 15:25 UTC
Labels: enhancement
