### ISSUE TITLE
eyedropper tool take colors from desktop's wallpaper

### ISSUE THREAD

**Issue by milenajb88** [ThePacielloGroup/CCAe#247] opened 2022-06-03 21:29 UTC
**Describe the bug**
When trying to pick a color from foreground or background the eyedropper tool does not take the color of the element in the window that I try to test, It takes the colors of the desktop's wallpaper

**Desktop (please complete the following information):**
 - OS: macOS Monterrey
 - Version 12.3.1

**To Reproduce**
1. Open the CCA
2. Click the eyedropper tool from foreground colour or background colour sections
3. Click the element under test

**Expected behavior**
The data displayed in CCA matches the data of the color from the element under test. 

**Current behavior**
The data displayed in CCA matches the data of the color from the desktop's wallpaper underneath.

**Screenshots**
![image](https://user-images.githubusercontent.com/44688058/171954861-b06496bc-e967-4091-a0c0-3f52466cc458.png)
![image](https://user-images.githubusercontent.com/44688058/171955524-ff3e5544-af2b-41e7-af66-69c729c3ff1c.png)

**Comment by greypants** [comment] 2022-06-07 16:33
looks like a duplicate of #241. See this comment for a workaround: https://github.com/ThePacielloGroup/CCAe/issues/241#issuecomment-1132866037

**Closed** 2022-06-24 08:25 UTC
