### ISSUE TITLE
Screen similator

### ISSUE THREAD

**Issue by mlamond** [ThePacielloGroup/CCAe#104] opened 2019-04-10 19:56 UTC
**Is your feature request related to a problem? Please describe.**
The previous version would allow you to preview a screen and click through the varying vision simulations. This is missing from the latest release. Another feature I used frequently.

**Describe the solution you'd like**
I'd like the screen preview/simulator added back to the tool.

**Comment by ferllings** [comment] 2019-04-11 06:52
Duplicate of #81

**Closed by ferllings** 2019-04-11 06:52 UTC
Labels: duplicate
