### ISSUE TITLE
An unannounced keyboard shortcut in CCA hijacks the macOS default for selecting text.

### ISSUE THREAD

**Issue by moverton** [ThePacielloGroup/CCAe#323] opened 2024-01-30 01:39 UTC
**Describe the bug**
In macOS, shift + command + right-arrow highlights text by default. However when CCA is running, this keyboard shortcut moves the CCA application panel from one display to another display and breaks the system default.

**Desktop (please complete the following information):**
 - OS: macOS Sonoma
 - Version 14.2.1 (23C71)

**To Reproduce**
Open CCA on macOS. Hit shift + command + right-arrow.

**Expected behavior**
shift + command + right-arrow should select text from the point of insertion to the end of the line.

**Screenshots**

**Additional context**

**Comment by handcoding** [comment] 2024-01-31 18:57
@moverton For whatever it’s worth, I think this bug report may be a duplicate of the [keyboard-shortcut-hijacking issue that I had reported here](https://github.com/ThePacielloGroup/CCAe/issues/305#issuecomment-1915745051) (or vice-versa)? 

Either way, I believe that it was [commit 7b953a6](https://github.com/ThePacielloGroup/CCAe/commit/7b953a64bac2a98474ef09f5ed741f2ad688162f) that caused this regression. And if we could get that commit backed out, I thiiiink that might resolve this.

**Comment by handcoding** [comment] 2024-01-31 18:59
And just for completeness—if it may help—here’s the text from the bug report that I had written:

> > Added similar feature on Macos [7b953a6](https://github.com/ThePacielloGroup/CCAe/commit/7b953a64bac2a98474ef09f5ed741f2ad688162f)
> 
> @ferllings By the way, I believe that the above commit has caused a regression that has the effect of breaking some standard macOS keyboard shortcuts within all macOS applications (whenever the Color Contrast Analyzer is running). 
> 
> As of CCA 3.5.1, if the Color Contrast Analyzer is running, the standard macOS keyboard shortcuts `Cmd+Shift+Left` and `Cmd+Shift+Right` no longer appear to work in *any application*. 
> 
> [macOS has standard keyboard shortcuts for selecting text](https://support.apple.com/en-us/HT201236#:~:text=Shift–Command–Down%20Arrow%3A,end%20of%20the%20current%20line.), and among them are:
> * `Cmd+Shift+Left` to select from the cursor position to the beginning of the line
> * `Cmd+Shift+Right` to select from the cursor position to the end of the line
> 
> Here are steps to reproduce this issue on macOS if it may help:
> 
> 1. Close the Color Contrast Analyzer if it may be running.
> 2. Open a new TextEdit document and paste in this text (or any other text):
>   `The quick brown fox jumped over the lazy dog.`
> 3. Place the cursor just after the word “fox” and then press `Cmd+Shift+Left`. 
>   * Result: ✔︎ The text from the cursor to the beginning of the line is selected.
> 4. Then open CCA 3.5.1 and repeat those steps:
>    1.  Go back to the open TextEdit document from earlier (with the “quick brown fox” text).
>    2. Place the cursor just after the word “fox” and then press `Cmd+Shift+Left`. 
> * Expected result: The text from the cursor to the beginning of the line is selected.
> * Actual result: Nothing happens.
> 
> Just for completeness: 
> * I’m running the Color Contrast Analyzer on macOS 14.2.1.
> * And I’ve also confirmed that this issue isn’t present when running CCA 3.4.2 for macOS.

**Comment by ferllings** [comment] 2024-02-01 12:27
As mentioned on the other topic. I'll probably make those shortcuts customizable. And find a better default combination

**Comment by A11yEvangel** [comment] 2024-05-01 20:50
(portable version 3.5.2) I never experienced a problem with Windows equivalent: Ctrl + Shift + arrow key. The latest version also is fine (in Windows 10 anyway).

**Comment by A11yEvangel** [comment] 2024-05-01 20:50
(portable version 3.5.2) I never experienced a problem with Windows equivalent: Ctrl + Shift + arrow key. The latest version also is fine (in Windows 10 anyway)

**Comment by poorgeek** [comment] 2024-09-06 19:12
Closing #346 as the duplicate of this issue was closed.

**Closed by poorgeek** 2024-09-06 19:12 UTC
Labels: bug
