### ISSUE TITLE
Zoom at Magnifier (Color Picker)

### ISSUE THREAD

**Issue by OLLI-S** [ThePacielloGroup/CCAe#134] opened 2019-10-09 10:28 UTC
**Is your feature request related to a problem? Please describe.**
With the new version of the CCA selecting the correct pixel is nearly impossible, because there is no zoom (magnifier) at the color picker mouse cursor.

**Describe the solution you'd like**
Please implement a zoom (magnifier) at the color picker (like you had it in CCA 2.1.
This makes the selection of the correct pixel much easier.

**Comment by ferllings** [comment] 2019-10-09 11:19
Duplicate of #122

**Closed by ferllings** 2019-10-09 11:19 UTC
