### ISSUE TITLE
Compatibility error - new 64 bit install on Win7 Enterprise Service Pack 1 machine

### ISSUE THREAD

**Issue by ChrisInTheWeb** [ThePacielloGroup/CCAe#121] opened 2019-06-12 04:36 UTC
Existing install failed to open, uninstalled, installed from TPG --> GitHub repo, 64 bit exe

Win7 Enterprise Service Pack 1 machine

Pixel picker magnifying glass fails to show underlying content for picking, only shows white. Machine 'Troubleshoot compatibility' test throws up 'Compatibility error' data, attached.

Expected to magnify rendered colours underneath. 

Algorithim re hex numbers still runs correctly

I notice an update was released 5 days ago.

![hex](https://user-images.githubusercontent.com/29972631/59323780-b1968100-8d0e-11e9-9ce1-7690d7be95de.png)
[hex.txt](https://github.com/ThePacielloGroup/CCAe/files/3279584/hex.txt)

**Comment by ferllings** [comment] 2019-06-12 06:24
Duplicate of #82

**Closed by ferllings** 2019-06-12 06:24 UTC
Labels: duplicate
