### ISSUE TITLE
what happened to f11 and f12 allowing the selection of foreground/background?

### ISSUE THREAD

**Issue by sasgrw** [ThePacielloGroup/CCAe#83] opened 2018-12-09 08:52 UTC
I have a new computer and just installed CCA.  I don't remember what my previous version number was but f11 and f12 were very handy for choosing foreground and background colors.  Those keys don't work in the new version.  Could they be added back, or add some shortcuts for the dropper?

**Comment by sasgrw** [comment] 2018-12-09 08:58
just looked up my previous version and it was 2.4

**Comment by ferllings** [comment] 2018-12-10 09:35
This is a complete rebuild of the CCA. I didn't knew about those shortcuts on the "classic" version
This sounds like a good idea. along with some other additional shortcuts.

**Comment by ferllings** [comment] 2019-04-05 11:39
Fixed in 2acd8b266f86616a1950f7c4f6afae41bad943df

**Comment by sasgrw** [comment] 2020-05-13 14:22
I just installed 3.0.1 and the F12 key is gone.  F11 is still there to select the foreground color but F12 to choose the background color does not work.

**Comment by ferllings** [comment] 2020-06-12 11:39
I can't reproduce: your F12 key is probably in conflict with another feature. Try to change the shortcut in the Preferences.

**Closed by ferllings** 2020-06-12 11:39 UTC
Labels: bug, can not replicate
