### ISSUE TITLE
Color picker not working

### ISSUE THREAD

**Issue by mfoley76** [ThePacielloGroup/CCAe#167] opened 2020-05-04 18:08 UTC
When I use the eye dropper tool and hover over an element - on the web or in other programs - the color that shows up in the eye dropper circle is not accurate or even close to being accurate. I have attached a few screenshots of the colors that are showing up compared to what they are hovering over. This program worked great for me for a few years but I have not been able to make it work in the last few weeks. I updated to 3.0.1 today in hopes it would resolve the issue, but it still isn't working properly
![Screenshot-Web](https://user-images.githubusercontent.com/64803025/80998294-8bcb0c80-8df7-11ea-96ed-47d859bead99.jpg)
![Screenshot-Photoshop](https://user-images.githubusercontent.com/64803025/80998299-8f5e9380-8df7-11ea-81a7-ed6ca81d4ab6.jpg)

.

**Comment by patrickhlauke** [comment] 2020-05-04 18:22
likely a duplicate of https://github.com/ThePacielloGroup/CCAe/issues/163 - need to ensure you granted appropriate permission to CCA

**Closed by patrickhlauke** 2020-05-04 18:22 UTC
